[package]
name = "eden"
description = "EDN parser"
license = "ISC"
version = "0.1.0"
authors = ["Luiz de Milon <luiz.de.milon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
